name: mini-sauras

on: [push]

jobs:
  read:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: mini-sauras
      uses: TeamTigers/mini-sauras@v0.0.4
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      id: dir
      with:
        directory: 'testing/'
        branch: 'test'