name: mini-sauras

on: [push]

jobs:
  read:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install terser
      run: |
        npm init -y
        npm i terser
    - name: mini-sauras
      uses: TeamTigers/mini-sauras@v0.0.2
      id: dir
      with:
        directory: './'